# Releasing Python 3.8.14, 3.9.14, and 3.10.7

The CPython versions 3.8.14, 3.9.14, and 3.10.7 were released some weeks
ago to mitigate
[CVE-2020-10735](https://nvd.nist.gov/vuln/detail/CVE-2020-10735). The
chosen mitigation strategy might cause errors (e.g.
`ValueError: Exceeds the limit (4300) for integer string conversion`) in
some libraries. If you are affected, please read the
[announcement](https://docs.python.org/release/3.10.7/whatsnew/3.10.html#notable-security-feature-in-3-10-7)
and learn about the available workarounds in the [CPython
documentation](https://docs.python.org/3/library/stdtypes.html#integer-string-conversion-length-limitation).

The conda-forge team [has
decided](https://github.com/conda-forge/python-feedstock/pull/579) to
build and publish these releases with no additional changes. The new
packages will be made available on or after 2022-11-10, following
[Anaconda's decision](https://anaconda.cloud/anaconda-repo-news).
